Отчет по Теме №11 выполнила:
- Лубянских Елизавета Дмитриевна
- ПИЭ-21-2

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

Работу проверили:
- к.э.н., доцент Панов М.А.

 ## Лабораторная работа №1
### Простой итератор, но у него нет гибкой настройки, например его нельзя развернуть. Он работает просто как next(), но нет prev()

```python
numbers = [0, 1, 2, 3, 4, 5]
for item in numbers:
    print(item)
```

### Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/33346d06-4bd2-4b14-bd97-3a4bb6136d23)

 ## Лабораторная работа №2
### Класс итератор с гибкой настройкой и удобными применением

```python
class CountDown:
    def __init__(self, start):
        self.count = start + 1

    def __iter__(self):
        return self

    def __next__(self):
        self.count -= 1
        if self.count < 0:
            raise StopIteration
        return self.count

if __name__ == '__main__':
    counter = CountDown(5)
    for i in counter:
        print(i)
```
### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/69f5132f-73d6-47fc-8234-daa32b340443)



 ## Лабораторная работа №3
### Генератор списка

```python
a = [i ** 2 for i in range(1, 5)]

print('a -', a)
for i in a:
    print(i)

print('iter(a) - ', iter(a))
for i in a:
    print(i)

```
### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/3c682697-dcba-41b7-be44-59b182edb7d4)


 ## Лабораторная работа №4
### Выражения генераторы

```python
b = (i ** 2 for i in range(1, 5))
print(b) #вывод не такой, как у генератора списков
print('first')
for i in b:
    print(i)
print('second')
#из-за особенностей выражения генераторов,
#они не будут выводиться больше одного раза
for i in b:
    print(i)
```

### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/b1fff8ce-c072-49d0-9e4c-068966db0265)


## Лабораторная работа №5
###  Такой же счетчик, как и в первом задании, только это генератор и использует yield

```python
def countdown(count):
    while count >= 0:
        yield count
        count -= 1

if __name__ == '__main__':
    counter = countdown(5)
    for i in counter:
        print(i)
```

### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/8f44cde2-8de4-4f2c-9933-11df8f6a2c77)


## Самостоятельная работа №1
### Вас никак не могут оставить числа Фибоначчи, очень уж они вас заинтересовали. Изучив новые возможности Python вы решили реализовать программу, которая считает числа Фибоначчи при помощи итераторов. Расчет начинается с чисел 1 и 1. Создайте функцию fib(n), генерирующую n чисел Фибоначчи с минимальными затратами ресурсов. Для реализации этой функции потребуется обратиться к инструкции yield (Она не сохраняет в оперативной памяти огромную последовательность, а дает возможность “доставать” промежуточные результаты по одному). Результатом решения задачи будет листинг кода и вывод в консоль с числом Фибоначчи от 200. 

```python
def fibonacci(n):
    a, b = 1, 1
    for i in range(n):
        yield a
        a, b = b, a + b

fibonacci_numbers = list(fibonacci(200))
print(fibonacci_numbers[-1])
```

### Результат
![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/4400ea9f-0c83-42fa-b648-a957ee4e0a23)

## Выводы.
### Итак, генераторы - это специальный тип функци йили выражений, которые позволяют создавать итераторы более эффективным способом. Они позволяют генерировать значения последовательно по одному элементу за раз без необходимости хранения всей последовательности в памяти. Для создания генераторов используется ключевое слово yield вместо return. Когда функция yield вызывается, она возвращает объект-генератор, а не результат выполнения функции.

 ## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такойпроблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(sm2):
    try:
        with open(sm2, 'r') as file:
            read_file = file.read()
            if not read_file:
                raise Exception("Файл пустой")
            else:
                print("Содержимое файла:")
                print(read_file)
    except FileNotFoundError:
        print(f"Файл {sm2} не найден")
    except Exception as e:
        print(f"Ошибка: {e}")

read_file('sm2.txt')
```
### Результат.

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/3baa04b3-c123-474d-a9fc-4aae957e560f)


## Выводы.
### В этом примере используется блок try-except для обработки исключений. Если файл не найден, программа выводит сообщение об этом. Если файл пустой, программа вызывает исключение с сообщением "Файл пустой". Если файл содержит информацию, она выводится в консоль.

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
# -*- coding: windows-1251 -*-
def add_two_numbers():
    try:
        user_input = input("Введите число: ")
        number = float(user_input)
        result = 2 + number
        print(f"Результат сложения 2 и {number}: {result}")
    except ValueError:
        print("Ошибка: Неподходящий тип данных. Ожидалось число.")

# Тест 1: ввод корректного числа
add_two_numbers()

# Тест 2: ввод строки
add_two_numbers()

# Тест 3: ввод другого неподходящего типа данных
add_two_numbers()
```
### Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/37da9999-0bdb-4ebe-86d1-af804ebd2ad1)


## Выводы. 
### В данной программе функция add_two_numbers считывает число, пробует преобразовать его в тип float и затем складывает с числом 2. Если пользователь вводит неподходящий тип данных, например, строку, программа перехватывает исключение ValueError и выводит соответствующее сообщение об ошибке.

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
import time

# Создаем класс декоратора
class CallInfoDecorator:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        # Запоминаем текущее время
        start_time = time.time()

        # Вызываем функцию и сохраняем ее результат
        result = self.func(*args, **kwargs)

        # Вычисляем время выполнения функции
        execution_time = time.time() - start_time

        # Выводим информацию о вызове функции
        print(f"Функция {self.func.__name__} была вызвана с аргументами {args} и ключевыми аргументами {kwargs}")
        print(f"Время выполнения функции: {execution_time} секунд\n")

        # Возвращаем результат функции
        return result

# Определяем две функции, к которым будем применять декоратор
@CallInfoDecorator
def multiply(x, y):
    return x * y

@CallInfoDecorator
def greet(name):
    return f"Привет, {name}!"

# Тестируем работу декоратора
result = multiply(5, 7)
print(result)  # Выведет: 35

result = greet("Вася")
print(result)  # Выведет: Привет, Вася!
```
## Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/8194a77c-17d2-4276-925c-dd4e5ea78b80)

## Выводы.
### Таким образом, декоратор CallInfoDecorator успешно применяется к функциям multiply и greet, и выводит информацию о вызове и времени выполнения каждой функции.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class CustomException(Exception):
    def __init__(self, message):
        super().__init__(message)
        self.message = message


def example_function(number):
    if number < 0:
        raise CustomException("Неверный ввод. Число должно быть положительным.")
    else:
        return number ** 2


try:
    input_number = int(input("Введите положительное число: "))
    result = example_function(input_number)
    print("Результат:", result)
except CustomException as e:
    print("Ошибка:", e.message)
```
### Результат

![image](https://github.com/llubyanskikh/Software_engineering0/assets/147454826/42a77012-22ea-4613-889d-ad52b8c050d2)

## Выводы. 
### В данном примере определен класс CustomException, который является наследником класса Exception. В конструкторе класса CustomException определена инициализация сообщения об ошибке. 

Затем определена функция example_function, которая получает на вход число и проверяет его значение. Если значение меньше нуля, то вызывается исключение CustomException с сообщением "Ошибка: Неверный ввод. Число должно быть положительным.". Иначе, функция возвращает квадрат введенного числа.

В основной части кода происходит запрос на ввод поло
